name: Deploy Reimbursement Calculator to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' depending on your repo
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # the folder containing your HTML file (update if needed)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
